Added third party jar jibx-run.jar, needed for beamSteer command paramater classes that are jibx annotated as they come from the database.

diff --git a/ioo/scripts/o_make_deployment b/ioo/scripts/o_make_deployment
--- a/ioo/scripts/o_make_deployment
+++ b/ioo/scripts/o_make_deployment
@@ -1,6 +1,6 @@
 #!/bin/csh
-# $Header: /space/home/eng/cjm/cvs/ioo/scripts/o_make_deployment,v 1.4 2012-05-29 14:03:13 cjm Exp $
-# Version: $Revision: 1.4 $
+# $Header: /space/home/eng/cjm/cvs/ioo/scripts/o_make_deployment,v 1.5 2012-07-10 13:32:15 cjm Exp $
+# Version: $Revision: 1.5 $
 # By $Author: cjm $
 # Make a deployment tar file.
 # This contains:
@@ -105,6 +105,42 @@ foreach jar ( ${jar_list} )
 	cp ${dev_bin_dir}/javalib/${jar} ${deployment_tmp_dir}
 	cd ${deployment_tmp_dir}
 	jar xvf ${jar} > ${deployment_tmp_dir}/jar_output.txt
+	find . -name '*.class' -print > ${deployment_tmp_dir}/class_list.txt
+	foreach class ( `cat ${deployment_tmp_dir}/class_list.txt` )
+		( ident ${class} > ${deployment_tmp_dir}/ident.txt ) >& ${deployment_tmp_dir}/ident_error.txt
+		set ident_string = `cat ${deployment_tmp_dir}/ident.txt`
+		echo "${ident_string}" >>! ${deployment_tmp_dir}/ident_list.txt
+	end
+	if ( -r ${deployment_tmp_dir}/ident_list.txt) then
+		cat ${deployment_tmp_dir}/ident_list.txt >>! ${deployment_icc_dir}/ident_list.txt 
+	endif
+# keep track of number of jars processed
+	@ jar_count ++
+end
+echo "${jar_count} jars copied."
+#
+# Copy third party jars
+#
+echo "Copying third party jars..."
+# jibx-run.jar is needed for beamSteer command parameter classes that are annotated as they come from the database
+set jar_list = "jibx/jibx-run.jar"
+set jar_count = 0
+foreach jar ( ${jar_list} )
+	echo "jar : ${jar}"
+# copy jar to deployment location
+	cp ${dev_bin_dir}/javalib_third_party/${jar} ${deployment_bin_dir}/javalib
+	set cp_status = $status
+	if( ${cp_status} != 0 ) then
+	    echo "Copy failed: ${dev_bin_dir}/javalib_third_party/${jar} to ${deployment_bin_dir}/javalib"
+	    exit 3
+	endif
+# ident contents of jar
+	cd ${deployment_dir}
+	rm -rf ${deployment_tmp_dir}
+	mkdir ${deployment_tmp_dir}
+	cp ${dev_bin_dir}/javalib_third_party/${jar} ${deployment_tmp_dir}
+	cd ${deployment_tmp_dir}
+	jar xvf ${jar:t} > ${deployment_tmp_dir}/jar_output.txt
 	find . -name '*.class' -print > ${deployment_tmp_dir}/class_list.txt
 	foreach class ( `cat ${deployment_tmp_dir}/class_list.txt` )
 		( ident ${class} > ${deployment_tmp_dir}/ident.txt ) >& ${deployment_tmp_dir}/ident_error.txt
@@ -411,6 +447,9 @@ echo "Download ${deployment_tar}.gz o_tar_install icc_cshrc icc_cshrc_edit.awk R
 echo "Deployment ready."
 #
 # $Log: not supported by cvs2svn $
+# Revision 1.4  2012/05/29 14:03:13  cjm
+# Changes to deploy E2V software (DSP) rather than Fairchild F486.
+#
 # Revision 1.3  2012/01/16 10:36:13  cjm
 # Swapped /icc/tmp/ for /icc/-o-data for o1.
 #
